#cmd=model.Model
index=model.IndexAction
hello=model.HelloAction
profile=model.ProfileAction
Test=model.TestAction
boardForm=model.board.BoardFormAction
boardAdd=model.board.BoardAddAction
boardPwdForm=model.board.BoardPwdFormAction
boardList=model.board.BoardListAction
boardDetail=model.board.BoardDetailAction
boardDelete=model.board.BoardDeleteAction
boardPwdchk=model.board.BoardPwdchkAction
boardUpdate=model.board.BoardUpdateAction